receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - 'http://*'
            - 'https://*'
          allowed_headers: ['*']

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusremotewriteexporter
  prometheusremotewrite:
    endpoint: 'http://prometheus:9090/api/v1/write'
    tls:
      insecure: true
    resource_to_telemetry_conversion:
      enabled: true

  logging/metrics:
    loglevel: debug

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
      processors: [batch]
