demo-pipeline:
  source:
    otel_logs_source:
      ssl: false
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        username: admin
        password: admin
        index: otel
